version: "3.8"
services:
    web:
        image: baxlash/bgapp-web
        deploy:
            replicas: 3
        ports:
            - 8080:80
        volumes:
            - "${PROJECT_ROOT}:/app:ro"
        networks:
            - app-network
        depends_on:
            - db
    db:
        image: baxlash/bgapp-db
        networks:
            - app-network
        environment:
            MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
networks:
    app-network:

